CREATE TABLE employment_profile_graph_data(
	AGGR_TYPE_CD text,
	S_MTCU text,
	OCCPTN_GRP_CD text,
	OCCPTN_SGRP_CD text,
	COLL_CD text,
	COLL_RGN_CD text,
	ACAD_GRAD_YEAR text,
	REPORTING_ACAD_YR text,
	GENDER text,
	GRAD_COUNT text,
	STUD_SAT_COUNT text,
	GENDER_PROP_RATE text,
	NUM_RESP_RATE text,
	NUM_RESP_RATE_ERROR text,
	UNEMP_RATE text,
	EMP_RATE text,
	EMP_FT_RATE text,
	EMP_PT_RATE text,
	JSD_RATE_FT_ALL_1 text,
	JSD_RATE_FT_ALL_2 text,
	JSD_RATE_FT_ALL_3 text,
	JSD_RATE_FT_ALL_4 text,
	JSD_RATE_FT_ALL_5 text,
	JSD_RATE_FT_RLTD_1 text,
	JSD_RATE_FT_RLTD_2 text,
	JSD_RATE_FT_RLTD_3 text,
	JSD_RATE_FT_RLTD_4 text,
	JSD_RATE_FT_RLTD_5 text,
	ANN_SLRY_EMP_FT_RATE text,
	ANN_CLRY_EMP_FT_RLTD_RATE text,
	GRAD_SAT_RATE_AGG text,
	GRAD_SAT_RATE_VD text,
	GRAD_SAT_RATE_D text,
	GRAD_SAT_RATE_N text,
	GRAD_SAT_RATE_S text,
	GRAD_SAT_RATE_VS text,
	EMP_SAT_RATE_AGGREGATE text,
	EMP_SAT_RATE_VD text,
	EMP_SAT_RATE_D text,
	EMP_SAT_RATE_N text,
	EMP_SAT_RATE_S text,
	EMP_SAT_RATE_VS text,
	IN_LF text,
	NOTIN_LF text,
	NOTIN_LF_PSNL_RATE text, 
	NOTIN_LF_EDUFT_RATE text,
	NOTIN_LF_EDUPT_RATE text,
	NOTIN_LF_OTHER_RATE text,
	NOTIN_LF_LM_PRESS_RATE text,
	NOTIN_LF_UKNW_RATE text, 
	NOTIN_LF_ND_RATE text,
	NOTINLF_FTSTUD_COLL text,
	NOTINLF_FTSTUD_UNIV text,
	NOTINLF_FTSTUD_OTH text,
	PT_PSNL_RATE text,
	PT_EDU_RATE text,
	PT_OTHER_RATE text,
	PT_LM_PRESS_RATE text,
	PTEMP_UKNW_RATE text,
	PTEMP_ND_RATE text,
	STUD_SAT_RATE text,
	GRADUATION_RATE text,
	EMP_FT_REL_RATE text,
	EMP_RES_RATE text,
	EMP_RES_RATE_ERROR text,
	GENDER_PROP_RANGE text,
	NUM_RESP_RANGE text,
	NUM_RESP_RANGE_ERROR text,
	UNEMP_RANGE text,
	EMP_RANGE text ,
	EMP_FT_RANGE text,
	EMP_PT_RANGE text,
	JSD_RANGEFT_ALL_1 text,
	JSD_RANGEFT_ALL_2 text,
	JSD_RANGEFT_ALL_3 text,
	JSD_RANGEFT_ALL_4 text,
	JSD_RANGEFT_ALL_5 text,
	JSD_RANGEFT_RLTD_1 text,
	JSD_RANGEFT_RLTD_2 text,
	JSD_RANGEFT_RLTD_3 text,
	JSD_RANGEFT_RLTD_4 text,
	JSD_RANGEFT_RLTD_5 text,
	ANN_SLRY_EMP_FT_RANGE text,
	ANN_CLRY_EMP_FT_RLTD_RANGE text,
	GRAD_SAT_RANGE_AGG text,
	GRAD_SAT_RANGE_VD text,
	GRAD_SAT_RANGE_D text,
	GRAD_SAT_RANGE_N text,
	GRAD_SAT_RANGE_S text,
	GRAD_SAT_RANGE_VS text,
	EMP_SAT_RANGE_AGG text,
	EMP_SAT_RANGE_VD text,
	EMP_SAT_RANGE_D text,
	EMP_SAT_RANGE_N text,
	EMP_SAT_RANGE_S text,
	EMP_SAT_RANGE_VS text,
	IN_LF_RANGE text,
	NOTIN_LF_RANGE text,
	NOTIN_LF_PSNL_RANGE text,
	NOTIN_LF_EDU_RANGE text,
	NOTIN_LF_EDUPT_RANGE text,
	NOTIN_LF_OTHER_RANGE text,
	NOTIN_LF_LM_PRESS_RANGE text,
	NOTIN_LF_UKNW_RANGE text,
	NOTIN_LF_ND_RANGE text,
	NOTINLF_FTSTUD_COLL_RANGE text,
	NOTINLF_FTSTUD_UNIV_RANGE text,
	NOTINLF_FTSTUD_OTH_RANGE text,
	PT_PSNL_RANGE text,
	PT_EDU_RANGE text,
	PT_OTHER_RANGE text,
	PT_LM_PRESS_RANGE text,
	PTEMP_UKNW_RANGE text,
	PTEMP_ND_RANGE text,
	STUD_SAT_RANGE text,
	GRADUATION_RANGES text,
	EMP_FT_REL_RANGE text,
	EMP_RES_RANGE text,
	EMP_RES_RANGE_ERROR text
);

create table employment_profile_naics_2(
AGGR_TYPE_CD text,
S_MTCU text,
OCCPTN_GRP_CD text,
OCCPTN_SGRP_CD text,
COLL_RGN_CD text,
COLL_CD text,
NAICS_CODE_RANK text,
NAICS_CODE_PERCENTAGE text,
NAICS_CODE integer,
NAICS_DESCRIPTION_ENGLISH text,
NAICS_DESCRIPTION_FRENCH text
);

create table employment_profile_noc_2(
AGGR_TYPE_CD text,
S_MTCU text,
OCCPTN_GRP_CD text,
OCCPTN_SGRP_CD text,
COLL_RGN_CD text,
COLL_CD text,
NOC_CODE_RANK integer,
NOC_CODE_PERCENTAGE integer,
NOC_CODE_CODE integer,
NOC_DESCRIPTION_ENGLISH text,
NOC_DESCRIPTION_FRENCH text
);

create table employment_profile_prognames(
S_MTCU text,
COLL_RGN_CD text,
COLL_CD text,
APSKey text,
APS_NAME text,
GRAD_OUT text,
STUD_SAT text,
GRAD_RATE text
);

create table ontario_skills_passport_osp_master(
	NOC_CD text,
	CAT_NAME text,
	TITLE text,
	DESCRIPTION text,
	EDUCATION_LEVEL_CD text,
	SKILL_ID text,
	SKILL text,
	Task_Description text,
	Task_Complexity_Level text
);

create table ojf_prospect_ratings(
	noc integer,
	title text,
	"2013_ojf_rating" text
);

create table college_enrolment_progcode(
	college_name text,
	mtcu_title text,
	head_count_fall text,
	mtcu_code integer,
	program_code text
);